# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ea5875790ff1aba86e2f624dc2a532eae9551daa9a274c4dea0b656918185f27acba0141104fb64bfeafb310dde9601e453d273eeefd9e386a180df45c8bbf0

test:
  secret_key_base: 2ec48449a1e1553b7f9fa39c9a650a91550b363411a0c9852cd7c180dcf250a96e0c51571bd081a098006416f8498fc2f488ad34d147254502b8403997478504

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
